version: '3.9'
services:
  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./vaultsetup/logs:/vault/logs
      - ./vaultsetup/data:/vault/data
      - ./vaultsetup/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/config.hcl